---
title: "ShinyApp Ross-Macdonald model"
author: Ottar N. Bjornstad
output: html_document
runtime: shiny
---

This Rmarkdown of the Ross-Macdonald model was written by Ottar N. Bjornstad and is released with a CC-BY-NC lisence for anyone to improve and re-share (acknowledging origin). Please email me a copy of update (onb1 at psu dot edu).

The app requires the shiny and deSolve packages to be installed to run. 

The basic equations are:
$$
dx/dt = (a b Y / X) y (1-x) -\gamma x \\
dy/dt = a c x (1-y)-  \mu y,
$$
where $x$ is fraction of infected humans, $y$ is fraction of infected mozzies, $m = Y/X$ is mossy-to-human ratio, $\gamma$ is human recovery rate, $1/\mu$ is mozzy life expectancy, $a$ is mozzy biting rate (1 / gono-cycle), $b$ is human probability of getting infected by infected mozzy, c is probability of mozzy infection from infected human.

The isoclines (sometimes called the nullclines) in this system are given by the solution to the 
equations $dx/dt=0$ and $dy/dt=0$ and partitions the phase plane into regions 
were $x$ and $y$ are increasing and decreasing. 
$$
y^*=\frac{\gamma x}{(a b m)(1-x)}\\
y^* =a c x / (a c x + \mu)
$$
The basic reproductive ratio ($R_0$) and endemic equilibrium ($\{x^*, y^*\}$) are:
$$
R_0 = m a^2 b c / \mu \gamma\\
x^*=(R_0-1)/[R_0 + a c / \mu]\\
y^*=(\frac{R_0 - 1}{R_0})(\frac{ac/\mu}{1+ac/\mu})
$$



The shiny app:

```{r, echo=FALSE}
require(shiny)
require(deSolve)
# This creates the User Interface (UI)
ui <- pageWithSidebar(
headerPanel(""),
sidebarPanel(
sliderInput("gamma", "gamma", 1/7,
              min = 1/356, max = 1),
sliderInput("a", "a", 1/4,
              min = 0, max = 1),
sliderInput("b", "b", 0.5,
              min = 0, max = 1),
sliderInput("c", "c", 0.9,
              min = 0, max = 1),
sliderInput("mu", "mu", 1/7,
              min = 1/28, max = 1),
sliderInput("m", "m", 10,
              min = 1, max = 100)
),
mainPanel(
  plotOutput("plot1", height = 500)
)
)


# This creates the 'behind the scenes' code (Server)
server <- function(input, output) {
grfn=function(t, Y, params){
  x=Y[1]
  y=Y[2]
  with(as.list(params),{
  dx=a*b*m*y*(1-x)-gamma*x
  dy=a*c*x*(1-y)-mu*y
  gr=c(dx, dy)
  list(gr)
  })
}


  output$plot1 <- renderPlot({
times=seq(0, 365*2, by=.1)

parms  = c(gamma = input$gamma, a =  input$a, b=input$b, c=input$c, mu=input$mu, m=input$m)
start=c(0.01, 0.01)

out=ode(y=start,
  times=times,
  func=grfn,
  parms=parms)

  out=as.data.frame(out)

with(as.list(parms),{
curve(gamma*x/((a*b*m)*(1-x)), 0,1, ylim=c(0,1), xlab="x", ylab="y")
R0=m*a^2*b*c/(mu*gamma)
title(paste ("R0=",R0))
curve(a*c*x/(a*c*x+mu), 0,1, add=TRUE, col="red")
})
points(out[,2], out[, 3])
legend("topleft", c("H isocline", "M isocline", "Trajectory"), lty=c(1,1,0), col=c(1,2, 1), pch=c(NA,NA, 1))
   })
  }

shinyApp(ui, server)
```

